### ISSUE TITLE
Error running test script

### ISSUE THREAD

**Issue by technophobicgeek** [cgs/evernote#1]
Hi there

On running the little test script in your README, I get the following error:

[evernote]$ ruby test_client.rb 
/usr/lib/ruby/gems/1.8/gems/evernote-0.8.0/vendor/gen-rb/evernote/edam/errors_types.rb:48:in `field_accessor': wrong number of arguments (3 for 2) (ArgumentError)
    from /usr/lib/ruby/gems/1.8/gems/evernote-0.8.0/vendor/gen-rb/evernote/edam/errors_types.rb:48
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/lib/ruby/gems/1.8/gems/evernote-0.8.0/vendor/gen-rb/evernote.rb:2
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/lib/ruby/gems/1.8/gems/evernote-0.8.0/lib/evernote.rb:7
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:36:in`gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from test_client.rb:1
[evernote]$ 

Does this mean your code needs an update? I'd very much appreciate one :)

Thanks
Raj

**Comment by cgs** [comment]
I have updated the vendored code - version 0.9.0 is now on Rubygems.org.
