### ISSUE TITLE
Auth example in README does not work

### ISSUE THREAD

**Issue by rubiojr** [cgs/evernote#10]
Installing thrift_client gem didn't help either.

/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:59:in `gem_original_require': no such file to load -- thrift_client/connection (LoadError)
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:59:in`require'
    from /usr/lib64/ruby/gems/1.8/gems/thrift_client-0.6.3/lib/thrift_client.rb:3
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in`require'
    from /usr/lib64/ruby/gems/1.8/gems/evernote-1.0.0/lib/evernote.rb:2
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:59:in `gem_original_require'
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:59:in`require'
    from ever.rb:2

I'm I missing something obvious?

**Comment by rubiojr** [comment]
Needs thrift_client version 0.6.0: 0.6.3 won't work.

add_dependency thrift_client, = 0.6.0 to gemspec?

**Comment by cgs** [comment]
Hmm, I'll take a look.

**Comment by rubiojr** [comment]
Thanks!

**Comment by cgs** [comment]
I tried a fresh install of the gem in an empty gemset and it worked ok (using thrift_client 0.6.3). What version of ruby are you using? Try 1.8.7 or above and see if that makes a difference.

**Comment by alainravet** [comment]
If you use Bundler :

``` ruby
# file: Gemfile
source :rubygems
gem "evernote"
```

``` ruby
# file: main.rb
require "rubygems"
require "bundler/setup"
require 'evernote'
# .. your code here
```

you'll see all the gems dependencies and versions in Gemfile.lock

```
# file: Gemfile.lock
GEM
  remote: http://rubygems.org/
  specs:
    evernote (1.1.0)
      thrift_client
    thrift (0.7.0)
    thrift_client (0.7.1)
      thrift (~> 0.7.0)

PLATFORMS
  ruby

DEPENDENCIES
  evernote
```

**Comment by pka** [comment]
I got the same error with this Gemfile.lock.

Fixing thrift_client file permissions solved the problem for me:

```
sudo chmod -R +r /var/lib/gems/1.8/gems/thrift_client-0.7.1/
```

**Comment by pka** [comment]
There's an open bug report for this: twitter/thrift_client#32

**Comment by ryanking** [comment]
I think the thrift_client bug is fixed. Please update and test.
