### ISSUE TITLE
NoteFilter EDAM Type Missing

### ISSUE THREAD

**Issue by rubiojr** [cgs/evernote#11]
Not sure if you autogenerate those...

https://gist.github.com/1080541

**Comment by MioGreen** [comment]
You can find it at https://github.com/cgs/evernote/blob/master/vendor/gen-rb/evernote/edam/note_store_types.rb

**Comment by rubiojr** [comment]
Damn it. Thanks.
I swear I grepped the code before opening... 0:-)

**Comment by MioGreen** [comment]
It is all right. :) Actually I created the pull request for last 1.19 version. I prefer to use evernote gem instead of my froked github repository.
