### ISSUE TITLE
Evernote API code out of date

### ISSUE THREAD

**Issue by sethhitch** [cgs/evernote#2]
Hi Chris, I noticed today that the Evernote API code in your gem is out of date. The current version 1.17 and can be downloaded from http://www.evernote.com/about/developer/api/.

Thanks,
Seth
Evernote

**Comment by cgs** [comment]
I have updated the vendored code - version 0.9.0 is now on Rubygems.org. Thanks for letting me know!

**Comment by ndbroadbent** [comment]
Thanks heaps! Was just about to update this myself.
