### ISSUE TITLE
Pass in parameters or hash instead of YML file

### ISSUE THREAD

**Issue by peetucket** [cgs/evernote#4]
Any chance you can update the code so we can pass in the api keys and username/passwords as parameters instead of with a YML file?  Working with a multi-user system, YML is not practical (nor should we assume configuration is coming from YML).  Basically you could just remove the load YML from the UserStore class and take in a hash instead...

cheers and thanks

**Comment by cgs** [comment]
Sure, feel free to fork and send me a pull request.
