### ISSUE TITLE
Using Gem on Windows Box

### ISSUE THREAD

**Issue by tylermcgill** [cgs/evernote#6]
When I try to install this gem on my windows box, I get the error "failed to build gem native extension".  I haven't run into this problem with any other gem before.  Is this a bug or am I missing something?

**Comment by cgs** [comment]
Hmm, I haven't tested the gem on windows so it could very well be a bug. Any more info you can give me would be great, and if you think you might be able to figure out what is going on that would be awesome. Thanks for reporting the issue!

**Comment by MioGreen** [comment]
I use it in my Windows 7. It works excelent. tylermcgill, may be you should install devkit from http://rubyinstaller.org/downloads/?

**Comment by tylermcgill** [comment]
@miogreen - you were right, I was missing devkit!  However although it got me past "failed to build gem native extension" I seem to now hit a wall with OpenSSL.  You said you've run it on Windows 7?  Whenever I try I get the following error:

OpenSSL::SSL::SSLError: SSL_Connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

I've tried disabling SSL verification, but that only changes the error to somehting different.  Any ideas?

**Comment by MioGreen** [comment]
Yes, I have the same error. And now I decide to use it without security. Just change your request api link from https to http.
