### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by Sjors** [cgs/evernote#8]
Evernote's API key request page suggests that one should use OAuth for web applications. I tend to agree, since I don't like the idea of storing lots of user passwords on my server. Evernote provides a ruby example in their SDK download that uses oauth (via https://github.com/oauth/oauth-ruby). Is it possible to modify this gem to use OAuth? How would one do that?

**Comment by cgs** [comment]
Hmm that might be possible, but I haven't looked into it. If you'd like to investigate feel free to fork and mess around with it.
