### ISSUE TITLE
'read_message_begin': No version identifier, old protocol client? (Thrift::ProtocolException)

### ISSUE THREAD

**Issue by ybakos** [cgs/evernote#9]
Using Ruby 1.9.2.

Steps to repeat:

gem install evernote

execute sample script in README.mkd

Full stack trace:

/...my gem path...//thrift-0.6.0/lib/thrift/protocol/binary_protocol.rb:122:in 'read_message_begin': No version identifier, old protocol client? (Thrift::ProtocolException)
    from /...my gem path...//thrift-0.6.0/lib/thrift/client.rb:45:in 'receive_message'
    from /...my gem path...//evernote-1.0.0/vendor/gen-rb/evernote/edam/user_store.rb:27:in 'recv_checkVersion'
    from /...my gem path...//evernote-1.0.0/vendor/gen-rb/evernote/edam/user_store.rb:19:in 'checkVersion'
    from /...my gem path...//thrift_client-0.6.3/lib/thrift_client/abstract_thrift_client.rb:130:in 'handled_proxy'
    from /...my gem path...//thrift_client-0.6.3/lib/thrift_client/abstract_thrift_client.rb:59:in 'checkVersion'
    from /...my gem path...//evernote-1.0.0/lib/evernote/client.rb:14:in 'method_missing'
    from /...my gem path...//evernote-1.0.0/lib/evernote/user_store.rb:35:in 'method_missing'
    from /...my gem path...//evernote-1.0.0/lib/evernote/user_store.rb:43:in 'version_valid?'
    from /...my gem path...//evernote-1.0.0/lib/evernote/user_store.rb:39:in 'validate_version'
    from /...my gem path...//evernote-1.0.0/lib/evernote/user_store.rb:25:in 'initialize'
    from en.rb:15:in 'new'
    from en.rb:15:in '<main>'

**Comment by rubiojr** [comment]
It happened to me. Make sure the sandbox URL is OK:

"https://sandbox.evernote.com/edam/user"

Do not replace the 'user' string in the URL path with your username.

**Comment by ybakos** [comment]
Thanks rubiojr. I thought "edam" was a username, not part of the base url. Also, dumbass here forgot to open a sandbox account and to get "client application" API credentials rather than the Webapp API creds. Shooo! And I thought I was a meticulous reader.
